FROM --platform=$BUILDPLATFORM golang:1-alpine AS builder
ARG TARGETARCH
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOARCH=$TARGETARCH go build -o http301 .

FROM scratch
COPY --from=builder /build/http301 /http301
ENTRYPOINT ["/http301"]
